spring:
  application:
    name: payment-ledger

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_ledger
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

jwt:
  secret: mySuperSecretJwtKeyForPaymentLedgerApplication123456
  expiration: 86400000